"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""
import analytic_io

def record_query_time(elapsed_ms):
    data = analytic_io.load_analytic()
    s = data["search"]

    s["total_queries"] += 1

    n = s["total_queries"]
    old_avg = s["avg_query_time_ms"]
    s["avg_query_time_ms"] = ((old_avg * (n - 1)) + elapsed_ms) / n

    if s["min_query_time_ms"] is None or elapsed_ms < s["min_query_time_ms"]:
        s["min_query_time_ms"] = elapsed_ms

    if elapsed_ms > s["max_query_time_ms"]:
        s["max_query_time_ms"] = elapsed_ms

    analytic_io.save_analytic(data)