"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import json
from pathlib import Path

ANALYTIC_PATH = Path("analytic.json")

DEFAULT_ANALYTICS = {
    "indexing": {
        # Indexed document count
        "num_document": 0,

        # Token counts
        "num_token_total": 0,
        "num_token_unigram": 0,
        "num_token_bigram": 0,
        "num_token_trigram": 0,

        # Duplicate counts
        "num_duplicate_total": 0,
        "num_duplicate_exact": 0,
        "num_duplicate_near": 0,

        # Index file sizes
        "index_size_kb_total_kb": 0,
        "index_size_kb_unigram_index": 0,
        "index_size_kb_bigram_index": 0,
        "index_size_kb_size_trigram_index": 0,
        "index_size_kb_doc_meta": 0,
        "index_size_kb_duplicate": 0,
        "index_size_kb_lexicon": 0,
    },
    "search": {
        "total_queries": 0,
        "avg_query_time_ms": 0.0,
        "max_query_time_ms": 0.0,
        "min_query_time_ms": None,
    }
}

def load_analytic():
    if ANALYTIC_PATH.exists():
        with ANALYTIC_PATH.open("r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        return DEFAULT_ANALYTICS.copy()

    return data

def save_analytic(data):
    with ANALYTIC_PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
